name: Node Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Update APT
      run: sudo apt update
    - name: Install LibreOffice
      run: sudo apt update && sudo apt install libreoffice
    - name: npm test
      run: |
        npm ci
        npm test
      env:
        CI: true
